<?php
header('Cache-Control: no-store');
header("Content-Security-Policy: default-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'");
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LINART · App privacy</title><link rel="stylesheet" href="admin.css"></head><body><header><a href="/">LINART<span>CONSTRUCTION INC.</span></a></header><main class="privacy"><h1>Your project. Your information.</h1><p>LINART app and Project Studio privacy notice · September 23, 2026</p>
<h2>Initial inquiries</h2><p>When you send an inquiry, Linart Construction Inc. receives your name, email address, phone number, project city or ZIP, project type and any optional description, timing and contact preference. Our website server records the inquiry, request IP address and submission time and sends it to our team by email. Sending an inquiry does not require a Studio account, photographs or a budget.</p>
<h2>Optional Project Studio</h2><p>Studio uses a one-time email code to verify access. This creates a passwordless Studio account. We use Supabase to process authentication and store cloud project records and private files. Selecting photos or documents does not upload them. Saving progress to LINART or submitting a brief sends your selected files, written answers, inspiration links and notes to LINART. Authorized personnel can review saved cloud drafts as well as submitted briefs.</p>
<p>Photo copies are converted to JPEG with source metadata removed. Uploaded PDFs may retain metadata from their original files. Upload only information and images you intend to share and have permission to provide. Private file download links expire after 60 seconds, but a recipient who downloads a copy may retain it.</p>
<h2>On your device</h2><p>The app stores saved portfolio choices, planning progress, the last inquiry email address, and protected local Studio drafts and selected file copies. Device backups may include local app files. The short-lived Studio access token is held in the device Keychain. The system photo and document pickers grant access only to items you select; the app does not request broad photo library, camera, contacts or location access.</p>
<h2>Use and sharing</h2><p>We use this information to respond to inquiries, understand your project, prepare for estimates and communicate with you. We do not sell Studio information, use it for targeted advertising or include advertising or analytics SDKs in the native app. Hosting, email and authentication providers process information to operate these services. Opening an external website, email app or sharing destination is subject to that provider’s privacy practices.</p>
<h2>Retention and deletion</h2><p>We keep inquiry and project information while responding to you and supporting the project. LINART reviews inactive records for deletion; contractual or other business records may need to be retained separately. You can remove selected cloud files by removing them from your Studio and saving again. Clearing local app data removes device copies, not cloud data.</p><p>Use “Delete my Studio account and cloud projects” in the Studio access screen to remove your account, cloud drafts, submitted briefs and uploaded files. This also removes local Studio drafts. Previously emailed inquiries, downloaded copies and separate business records are not automatically recalled. Provider backups may retain deleted information until their backup retention period expires. For access, corrections or deletion of those separate records, contact us.</p>
<h2>Contact LINART</h2><p><a href="mailto:services@linartinc.com">services@linartinc.com</a> · <a href="tel:6092097810">609-209-7810</a></p></main></body></html>
