// Browser interaction and responsive checks against fixtures; no real client data.
import {createRequire} from 'node:module';
import fs from 'node:fs';
import http from 'node:http';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const publicDir=new URL('../apps/web/public/',import.meta.url);
const project={id:'10000000-0000-4000-8000-000000000001',contact:{name:'Test Client <script>alert(1)</script>',email:'client@example.invalid',phone:'6095550100',city:'Test Township',service:'Kitchen Remodeling',contact:'Email',timing:'',message:'Test only'},created_at:'2026-09-23T12:00:00Z',status:'New Inquiry',delivery:'accepted',deletion_requested_at:null,linart_studios:{revision:2,submitted_revision:1,submitted_at:'2026-09-23T13:00:00Z'}};
let signedIn=false,updates=0;
const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url==='/studio.php'){let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);res.setHeader('Content-Type','application/json');if(body.action==='send_code'){res.end('{"ok":true}');return;}if(body.action==='verify_code'){signedIn=true;res.end('{"ok":true}');return;}if(!signedIn){res.statusCode=401;res.end('{"error":"Sign in required"}');return;}let out={ok:true};if(body.action==='list')out={admin:true,projects:[project]};if(body.action==='get')out={project,studio:{answers:{goals:'A bright family kitchen',style:'Warm oak'},links:[{url:'https://example.invalid/inspiration',note:'Daylight'}],revision:2,submitted_revision:1,submitted_at:'2026-09-23T13:00:00Z',submitted_brief:{answers:{goals:'Original'}}},assets:[]};if(body.action==='status'){project.status=body.status;updates++;}if(body.action==='logout')signedIn=false;res.end(JSON.stringify(out));return;}const name=req.url==='/'?'studio-admin.php':req.url.slice(1);if(!['studio-admin.php','studio-admin.js','studio-admin.css'].includes(name)){res.statusCode=404;res.end();return;}let data=fs.readFileSync(new URL(name,publicDir),'utf8');if(name.endsWith('.php'))data=data.slice(data.indexOf('<!doctype'));res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.js')?'text/javascript':'text/html');res.end(data);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || chromium.executablePath(),args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('#login').waitFor({state:'visible'});assert.equal(await page.locator('#desk').isVisible(),false);await page.fill('#email','admin@example.invalid');await page.click('#send-code');await page.fill('#code','123456');await page.click('#verify');await page.locator('#desk').waitFor({state:'visible'});await page.locator('#projects button').click();await page.getByRole('heading',{name:'Goals & scope'}).waitFor();assert.ok((await page.locator('#brief').innerText()).includes('Useful follow-up'));assert.equal(await page.locator('#brief script').count(),0);await page.locator('#brief select').selectOption('Contacted');await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Project status updated.');assert.equal(updates,1);fs.mkdirSync('/tmp/linart-previews',{recursive:true});await page.screenshot({path:'/tmp/linart-previews/admin-desktop.png',fullPage:true});for(const [name,width,height] of [['ipad',834,1112],['phone',390,844]]){await page.setViewportSize({width,height});await page.screenshot({path:`/tmp/linart-previews/admin-${name}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`${name} overflow`);}await page.click('#logout');await page.locator('#login').waitFor({state:'visible'});assert.equal(await page.locator('#brief').innerText(),'');assert.deepEqual(errors,[]);console.log('PASS admin login, authorization shell, inquiry detail, literal client text, missing context, status, sign-out data clearing, desktop/iPad/phone overflow; no browser exceptions.');}finally{await browser.close();server.close();}
