import React from 'react';

/**
 * Responsive <img> wrapper.
 *
 * Every .webp in public/images has -480 / -960 / -1600 variants generated by
 * `node tools/optimize-images.mjs`. This component emits the srcset so a
 * thumbnail downloads the 480px file instead of the 1600px original.
 *
 * `sizes` is the important prop: it tells the browser how wide the image will
 * actually render, so it can pick the right file BEFORE layout. Get it wrong
 * and the browser over-downloads. Guidance:
 *   full-bleed hero .......... "100vw"
 *   half-width feature ....... "(min-width: 1024px) 50vw, 100vw"
 *   thumbnail in a 3-up strip  "(min-width: 1024px) 15vw, 30vw"
 */

const WIDTHS = [480, 960, 1600];

const Img = ({ src, alt, sizes = '100vw', priority = false, ...rest }) => {
  const webp = typeof src === 'string' && /\.webp$/i.test(src);

  if (!webp) {
    return <img src={src} alt={alt} loading={priority ? 'eager' : 'lazy'} decoding="async" {...rest} />;
  }

  const base = src.replace(/\.webp$/i, '');

  return (
    <img
      src={`${base}-960.webp`}
      srcSet={WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(', ')}
      sizes={sizes}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : 'auto'}
      decoding="async"
      {...rest}
    />
  );
};

export default Img;
