import React from 'react';
import { responsiveImages } from '@/generated/imageManifest';

/**
 * Responsive <img> wrapper.
 *
 * Optimized variants and their true pixel widths are generated by
 * `npm run images:optimize`. Images missing from the manifest gracefully use
 * their original source, so adding a new photo never creates broken requests.
 *
 * `sizes` is the important prop: it tells the browser how wide the image will
 * actually render, so it can pick the right file BEFORE layout. Get it wrong
 * and the browser over-downloads. Guidance:
 *   full-bleed hero .......... "100vw"
 *   half-width feature ....... "(min-width: 1024px) 50vw, 100vw"
 *   thumbnail in a 3-up strip  "(min-width: 1024px) 15vw, 30vw"
 */

const Img = ({ src, alt, sizes = '100vw', priority = false, ...rest }) => {
  const image = typeof src === 'string' ? responsiveImages[src] : undefined;

  if (!image) {
    return (
      <img
        src={src}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : undefined}
        decoding="async"
        {...rest}
      />
    );
  }

  const base = src.replace(/\.webp$/i, '');
  const fallbackWidth = image.candidates.at(-1);

  return (
    <img
      src={`${base}-${fallbackWidth}.webp`}
      srcSet={image.candidates.map((width) => `${base}-${width}.webp ${width}w`).join(', ')}
      sizes={sizes}
      alt={alt}
      width={image.width}
      height={image.height}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : undefined}
      decoding="async"
      {...rest}
    />
  );
};

export default Img;
